# Input variables (based on physicochemical test)
1. fixed acidity 
2. volatile acidity
3. citric acid
4. residual sugar
5. chlorides
6. free sulfur dioxide 
7. total surfur dioxide
8. density
9. pH
10. sulphates
11. alcohol
<hr>
12. quality ( score between 0 and 10) 

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns


In [ ]:
data_path='dataset/winequality-red.csv'
winedf=pd.read_csv(data_path)
winedf

In [ ]:
winedf.shape


In [ ]:
winedf.count()

In [ ]:
winedf.describe()

In [ ]:
winedf.info()

In [ ]:
winedf.isnull().sum()

In [ ]:
#checking for outliers

for i in winedf.columns:
    sns.boxplot(x=winedf[i])
    plt.show()

In [ ]:
plt.figure(figsize=(20,10))
sns.heatmap(winedf.corr(),annot=True)
plt.show()

In [ ]:
#create a copy for visualization
winedf_copy=winedf.copy()

In [ ]:
#plotting the counts of category

winedf_copy.quality=winedf_copy.quality.map({0:'0',1:'1',2:'2',3:'3',4:'4',5:'5',6:'6',7:'7',8:'8',9:'9',10:'10'})
sns.countplot(x="quality",data=winedf_copy)

In [ ]:
#draw kde plot

winedf_copy['fixed acidity'].plot.kde()

In [ ]:
winedf_copy['volatile acidity'].plot.kde()

In [ ]:
#compare quality witg other columns

sns.boxplot(x=winedf_copy['quality'],y=winedf_copy['fixed acidity'])
plt.title("fixed acidity vs quality")

In [ ]:

sns.boxplot(x=winedf_copy['quality'],y=winedf_copy['volatile acidity'])
plt.title("fixed acidity vs quality")

In [ ]:
x=winedf.drop('quality',axis=1)
y=winedf.quality

In [ ]:
x.head()

In [ ]:
x.shape

In [ ]:
y.head()

In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers

In [ ]:
#defining the sequential model for binary classification

model=keras.Sequential()

In [ ]:
model.add(layers.Dense(11,activation='relu',input_dim=11))
model.add(layers.Dense(5,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))

In [ ]:
#compile and fit the model 
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x,y,validation_split=0.22,batch_size=100,epochs=20)
model.summary()


In [ ]:
#plot graph

plt.plot(history.history['loss'])
plt.plot(history.history["val_loss"])
plt.ylabel("loss")
plt.xlabel("epoch")
plt.show()

In [ ]:

plt.plot(history.history['accuracy'])
plt.plot(history.history["val_accuracy"])
plt.ylabel("accuracy")
plt.xlabel("epoch")
plt.show()

In [100]:
import numpy 
from numpy import array

xnew=np.array([[7.6,0.6,0.06,1.6,0.069,15.0,59.0,0.9964,3.3,0.46,9.4]])
xnew=np.array(xnew,dtype=np.float64)

In [101]:
xnew

array([[ 7.6   ,  0.6   ,  0.06  ,  1.6   ,  0.069 , 15.    , 59.    ,
         0.9964,  3.3   ,  0.46  ,  9.4   ]])

In [103]:
ynew=model.predict(xnew)
ynew
maxindex=np.argmax(ynew,axis=1)
maxindex

1/1 [==============================] - 0s 47ms/step


array([5], dtype=int64)

In [104]:
model.save("winemodel.h5")

d:\localdata\anaconda\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [105]:
from tensorflow.keras.models import load_model

In [106]:
loaded_model=load_model("winemodel.h5")

In [107]:
import numpy 
from numpy import array

xnew=np.array([[7.6,0.6,0.06,1.6,0.069,15.0,59.0,0.9964,3.3,0.46,9.4]])
xnew=np.array(xnew,dtype=np.float64)
ynew=loaded_model.predict(xnew)
ynew
maxindex=np.argmax(ynew,axis=1)
maxindex

1/1 [==============================] - 0s 83ms/step


array([5], dtype=int64)